# fly.toml app configuration file generated for viadukt-wild-glitter-283 on 2023-12-10T21:50:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "viadukt-wild-glitter-283"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
